version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch
    ignore:
      # Must match nodejs runtime version
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major
      # Must match octokit version used by @actions/github
      - dependency-name: '@octokit/plugin-request-log'
        update-types:
          - version-update:semver-major
