name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '18 11 * * 6'

defaults:
  run:
    shell: bash

jobs:
  dist-check:
    runs-on: ubuntu-slim

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: package.json

      - run: npm ci
      - run: npm run build

      - id: diff
        run: git diff --exit-code --color --ignore-space-at-eol --text dist/

      - if: ${{ always() && steps.diff.outcome == 'failure' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist
          path: dist/

  eslint:
    runs-on: ubuntu-slim

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: package.json

      - run: npm ci
      - run: npm run build
      - run: npm run lint

  prettier:
    runs-on: ubuntu-slim

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: package.json

      - run: npm ci
      - run: npm run format && git diff --color --exit-code

  actionlint:
    runs-on: ubuntu-slim

    permissions:
      contents: read

    env:
      # renovate: datasource=github-releases depName=rhysd/actionlint
      ACTIONLINT_VERSION: 1.7.12

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - working-directory: ${{ runner.temp }}
        run: |
          wget "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz"
          mkdir actionlint
          tar -C actionlint -xf "actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz"
          echo "$(pwd)/actionlint" >>"$GITHUB_PATH"
          wget "https://raw.githubusercontent.com/rhysd/actionlint/v${ACTIONLINT_VERSION}/.github/actionlint-matcher.json"
          echo "::add-matcher::$(pwd)/actionlint-matcher.json"

      - run: actionlint -verbose -color

  test:
    if: >-
      github.event.pull_request.head.repo.node_id == github.event.pull_request.base.repo.node_id
      || !github.event.pull_request

    needs:
      - dist-check

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - head: head_sha
            draft: no_draft
          - head: no_head_sha
            draft: draft

    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      GH_PR_FIELDS: number,title,body,isDraft,state,headRefName,headRefOid,baseRefName,url

      COMMIT_BRANCH_NAME: testing-commit-${{ github.run_id }}-${{ strategy.job-index }}
      PR_HEAD_BRANCH: testing-pr-${{ github.run_id }}-${{ strategy.job-index }}
      PR_BASE_BRANCH: main
      PR_DRAFT: ${{ matrix.draft == 'draft' }}

      TITLE1: Test pull request ${{ matrix.draft }} ${{ matrix.head }} title
      BODY1: Test pull request ${{ matrix.draft }} ${{ matrix.head }} body

      TITLE2: Test pull request ${{ matrix.draft }} ${{ matrix.head }} title 2
      BODY2: Test pull request ${{ matrix.draft }} ${{ matrix.head }} body 2

    steps:
      - name: 'Checkout: action source'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: 'Checkout: working directory for tests'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ env.PR_BASE_BRANCH }}
          path: testing
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name 'Test'
          git config --global user.email 'test@example.com'

      - name: Add a test commit
        working-directory: testing
        run: |
          echo "BASE_SHA=$(git rev-parse HEAD)" >>"$GITHUB_ENV"
          git checkout -b "$COMMIT_BRANCH_NAME"
          echo Test >test-file-1.txt
          git add test-file-1.txt
          git commit -m 'Test Commit 1'
          git push -u origin "$COMMIT_BRANCH_NAME"
          echo "COMMIT1_SHA=$(git rev-parse HEAD)" >>"$GITHUB_ENV"

      - name: Create PR head branch
        if: ${{ matrix.head == 'no_head_sha' }}
        working-directory: testing
        run: |
          git checkout -b "$PR_HEAD_BRANCH"
          git push -u origin "$PR_HEAD_BRANCH"

      - name: Create pull request
        id: pr-create
        uses: ./.
        with:
          title: ${{ env.TITLE1 }}
          body: ${{ env.BODY1 }}
          update: false
          draft: ${{ env.PR_DRAFT }}
          head: ${{ env.PR_HEAD_BRANCH }}
          head_sha: ${{ case(matrix.head == 'head_sha', env.COMMIT1_SHA, '') }}
          base: ${{ env.PR_BASE_BRANCH }}

      - name: Get pull request using GitHub CLI
        env:
          PR_NUMBER: ${{ steps.pr-create.outputs.number }}
        run: gh pr view "$PR_NUMBER" --json "$GH_PR_FIELDS" | jq -S -f test/gh-cli-filter.jq >"$RUNNER_TEMP/github-cli.json"

      - name: Verify action output matches GitHub CLI output
        env:
          ACTION_OUTPUT_JSON: ${{ steps.pr-create.outputs.pull_request }}
        run: diff -u <(printf '%s' "$ACTION_OUTPUT_JSON" | jq -S -f test/action-output-filter.jq) "$RUNNER_TEMP/github-cli.json"

      - name: Verify pull request matches inputs
        env:
          PR_NUMBER: ${{ steps.pr-create.outputs.number }}
          PR_HTML_URL: ${{ steps.pr-create.outputs.html_url }}
          PR_HEAD_SHA: ${{ env.COMMIT1_SHA }}
          PR_TITLE: ${{ env.TITLE1 }}
          PR_BODY: ${{ env.BODY1 }}
        run: diff -u <(jq -n -S -f test/expected-filter.jq) "$RUNNER_TEMP/github-cli.json"

      - name: 'Run action with the same inputs (except update: true)'
        id: pr-same-input
        uses: ./.
        with:
          title: ${{ env.TITLE1 }}
          body: ${{ env.BODY1 }}
          update: true
          draft: ${{ env.PR_DRAFT }}
          head: ${{ env.PR_HEAD_BRANCH }}
          head_sha: ${{ case(matrix.head == 'head_sha', env.COMMIT1_SHA, '') }}
          base: ${{ env.PR_BASE_BRANCH }}

      - run: sleep 10

      - name: Get pull request using GitHub CLI
        env:
          PR_NUMBER: ${{ steps.pr-same-input.outputs.number }}
        run: gh pr view "$PR_NUMBER" --json "$GH_PR_FIELDS" | jq -S -f test/gh-cli-filter.jq >"$RUNNER_TEMP/github-cli-2.json"

      - name: Verify there has been no changes
        run: diff -u "$RUNNER_TEMP/github-cli.json" "$RUNNER_TEMP/github-cli-2.json"

      - name: Verify action output matches GitHub CLI output
        env:
          ACTION_OUTPUT_JSON: ${{ steps.pr-same-input.outputs.pull_request }}
        run: diff -u <(printf '%s' "$ACTION_OUTPUT_JSON" | jq -S -f test/action-output-filter.jq) "$RUNNER_TEMP/github-cli-2.json"

      - name: Add second commit
        working-directory: testing
        run: |
          git checkout "$COMMIT_BRANCH_NAME"
          echo Test 2 >test-file-2.txt
          git add test-file-2.txt
          git commit -m 'Test Commit 2'
          git push -u origin "$COMMIT_BRANCH_NAME"
          echo "COMMIT2_SHA=$(git rev-parse HEAD)" >>"$GITHUB_ENV"

      - name: 'Run action with new inputs (but update: false)'
        id: pr-no-update
        uses: ./.
        with:
          title: ${{ env.TITLE2 }}
          body: ${{ env.BODY2 }}
          update: false
          draft: ${{ env.PR_DRAFT }}
          head: ${{ env.PR_HEAD_BRANCH }}
          head_sha: ${{ case(matrix.head == 'head_sha', env.COMMIT2_SHA, '') }}
          base: ${{ env.PR_BASE_BRANCH }}

      - run: sleep 10

      - name: Get pull request using GitHub CLI
        env:
          PR_NUMBER: ${{ steps.pr-no-update.outputs.number }}
        run: gh pr view "$PR_NUMBER" --json "$GH_PR_FIELDS" | jq -S -f test/gh-cli-filter.jq >"$RUNNER_TEMP/github-cli-3.json"

      - name: Verify there has been no changes
        run: diff -u "$RUNNER_TEMP/github-cli.json" "$RUNNER_TEMP/github-cli-3.json"

      - name: Verify action output matches GitHub CLI output
        env:
          ACTION_OUTPUT_JSON: ${{ steps.pr-no-update.outputs.pull_request }}
        run: diff -u <(printf '%s' "$ACTION_OUTPUT_JSON" | jq -S -f test/action-output-filter.jq) "$RUNNER_TEMP/github-cli-3.json"

      - name: Update PR head branch
        if: ${{ matrix.head == 'no_head_sha' }}
        working-directory: testing
        run: |
          git checkout "$PR_HEAD_BRANCH"
          git reset --hard "$COMMIT_BRANCH_NAME"
          git push -u origin "$PR_HEAD_BRANCH"

      - run: sleep 10
        if: ${{ matrix.head == 'no_head_sha' }}

      - name: 'Run action with new inputs, update PR'
        id: pr-update
        uses: ./.
        with:
          title: ${{ env.TITLE2 }}
          body: ${{ env.BODY2 }}
          update: true
          draft: ${{ env.PR_DRAFT }}
          head: ${{ env.PR_HEAD_BRANCH }}
          head_sha: ${{ case(matrix.head == 'head_sha', env.COMMIT2_SHA, '') }}
          base: ${{ env.PR_BASE_BRANCH }}

      - run: sleep 10

      - name: Get pull request using GitHub CLI
        env:
          PR_NUMBER: ${{ steps.pr-update.outputs.number }}
        run: gh pr view "$PR_NUMBER" --json "$GH_PR_FIELDS" | jq -S -f test/gh-cli-filter.jq >"$RUNNER_TEMP/github-cli-4.json"

      - name: Verify action output matches GitHub CLI output
        env:
          ACTION_OUTPUT_JSON: ${{ steps.pr-update.outputs.pull_request }}
        run: diff -u <(printf '%s' "$ACTION_OUTPUT_JSON" | jq -S -f test/action-output-filter.jq) "$RUNNER_TEMP/github-cli-4.json"

      - name: Verify pull request matches inputs
        env:
          PR_NUMBER: ${{ steps.pr-update.outputs.number }}
          PR_HTML_URL: ${{ steps.pr-update.outputs.html_url }}
          PR_HEAD_SHA: ${{ env.COMMIT2_SHA }}
          PR_TITLE: ${{ env.TITLE2 }}
          PR_BODY: ${{ env.BODY2 }}
        run: diff -u <(jq -n -S -f test/expected-filter.jq) "$RUNNER_TEMP/github-cli-4.json"

      - name: Delete pr branch
        if: ${{ always() }}
        run: git push origin ":$PR_HEAD_BRANCH"
        working-directory: testing

      - name: Delete commit branch
        if: ${{ always() && env.PR_HEAD_BRANCH != env.COMMIT_BRANCH_NAME }}
        run: git push origin ":$COMMIT_BRANCH_NAME"
        working-directory: testing
