name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '18 11 * * 6'

defaults:
  run:
    shell: bash

jobs:
  dist-check:
    runs-on: ubuntu-slim

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: package.json

      - run: npm ci
      - run: npm run build

      - id: diff
        run: git diff --exit-code --color --ignore-space-at-eol --text dist/

      - if: ${{ always() && steps.diff.outcome == 'failure' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist
          path: dist/

  eslint:
    runs-on: ubuntu-slim

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: package.json

      - run: npm ci
      - run: npm run build
      - run: npm run lint

  prettier:
    runs-on: ubuntu-slim

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: package.json

      - run: npm ci
      - run: npm run format && git diff --color --exit-code

  actionlint:
    runs-on: ubuntu-slim

    permissions:
      contents: read

    env:
      # renovate: datasource=github-releases depName=rhysd/actionlint
      ACTIONLINT_VERSION: 1.7.12

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - working-directory: ${{ runner.temp }}
        run: |
          wget "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz"
          mkdir actionlint
          tar -C actionlint -xf "actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz"
          echo "$(pwd)/actionlint" >>"$GITHUB_PATH"
          wget "https://raw.githubusercontent.com/rhysd/actionlint/v${ACTIONLINT_VERSION}/.github/actionlint-matcher.json"
          echo "::add-matcher::$(pwd)/actionlint-matcher.json"

      - run: actionlint -verbose -color

  test-setup:
    needs: dist-check

    if: >-
      ${{
        !github.event.pull_request ||
        github.event.pull_request.head.repo.node_id == github.event.pull_request.base.repo.node_id
      }}

    runs-on: ubuntu-slim

    permissions:
      contents: write

    outputs:
      commit-branch: ${{ steps.branch-names.outputs.commits }}
      base-branch: ${{ steps.branch-names.outputs.base }}
      commits: >-
        ${{
          format(
            '["{0}", "{1}", "{2}"]',
            steps.commit0.outputs.sha,
            steps.commit1.outputs.sha,
            steps.commit2.outputs.sha
          )
        }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name 'Test'
          git config --global user.email 'test@example.com'

      - name: Generate branch names
        id: branch-names
        run: |
          echo "commits=testing-commit-$GITHUB_RUN_ID" | tee -a "$GITHUB_OUTPUT"
          echo "base=testing-base-$GITHUB_RUN_ID" | tee -a "$GITHUB_OUTPUT"

      - name: Start orphan branch
        run: |
          git checkout --orphan "$COMMIT_BRANCH"
          git rm -rf .
        env:
          COMMIT_BRANCH: ${{ steps.branch-names.outputs.commits }}

      - name: Initial commit
        id: commit0
        run: |
          git commit --allow-empty -m 'Initial empty commit'
          echo "sha=$(git rev-parse HEAD)" | tee -a "GITHUB_OUTPUT"

      - name: Start base branch
        run: |
          git checkout -b "$BASE_BRANCH"
          git push -u origin "$BASE_BRANCH"
          git checkout "$COMMIT_BRANCH"
        env:
          BASE_BRANCH: ${{ steps.branch-names.outputs.base }}
          COMMIT_BRANCH: ${{ steps.branch-names.outputs.commits }}

      - name: Commit 1
        id: commit1
        run: |
          echo Test commit 1 >test-file.txt
          git add test-file.txt
          git commit -m 'Test Commit 1'
          echo "sha=$(git rev-parse HEAD)" | tee -a "$GITHUB_OUTPUT"

      - name: Commit 2
        id: commit2
        run: |
          echo Test commit 2 >test-file.txt
          git add test-file.txt
          git commit -m 'Test Commit 2'
          echo "sha=$(git rev-parse HEAD)" | tee -a "$GITHUB_OUTPUT"

      - name: Push commits
        run: git push -u origin "$COMMIT_BRANCH"
        env:
          COMMIT_BRANCH: ${{ steps.branch-names.outputs.commits }}

  test-teardown:
    needs:
      - test-setup
      - test

    if: ${{ always() && needs.test-setup.result != 'skipped' }}
    runs-on: ubuntu-slim

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true

      - name: Delete commit branch
        run: git push origin ":$BRANCH"
        continue-on-error: true
        env:
          BRANCH: ${{ needs.test-setup.outputs.commit-branch }}

      - name: Delete base branch
        run: git push origin ":$BRANCH"
        continue-on-error: true
        env:
          BRANCH: ${{ needs.test-setup.outputs.base-branch }}

  test:
    needs: test-setup

    runs-on: ubuntu-slim

    permissions:
      contents: write
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - draft: no-draft
            force: no-force
            update: update
            use-head-sha: no-use-head-sha
            success: success
            commit1: 1
            commit2: 2

          - draft: draft
            force: no-force
            update: update
            use-head-sha: use-head-sha
            success: success
            commit1: 1
            commit2: 2

          - draft: no-draft
            force: no-force
            update: update
            use-head-sha: use-head-sha
            success: no-success
            commit1: 2
            commit2: 1

          - draft: no-draft
            force: force
            update: update
            use-head-sha: use-head-sha
            success: success
            commit1: 2
            commit2: 1

          - draft: no-draft
            force: no-force
            update: no-update
            use-head-sha: use-head-sha
            success: success
            commit1: 2
            commit2: 1

    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      GH_PR_FIELDS: number,title,body,isDraft,state,headRefName,headRefOid,baseRefName,url

      PR_HEAD_BRANCH: testing-pr-${{ github.run_id }}-${{ strategy.job-index }}
      PR_BASE_BRANCH: ${{ needs.test-setup.outputs.base-branch }}

      TITLE1: Test pull request ${{ github.run_id }} ${{ strategy.job-index }} title
      BODY1: Test pull request ${{ github.run_id }} ${{ strategy.job-index }} body

      TITLE2: Test pull request ${{ github.run_id }} ${{ strategy.job-index }} title 2
      BODY2: Test pull request ${{ github.run_id }} ${{ strategy.job-index }} body 2

      COMMIT1: ${{ fromJSON(needs.test-setup.outputs.commits)[matrix.commit1] }}
      COMMIT2: ${{ fromJSON(needs.test-setup.outputs.commits)[matrix.commit2] }}

    steps:
      - name: 'Checkout: action source'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: 'Checkout: working directory for tests'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ needs.test-setup.outputs.base-branch }}
          path: testing
          persist-credentials: true

      - name: Create PR head branch
        if: ${{ matrix.use-head-sha != 'use-head-sha' }}
        working-directory: testing
        run: |
          git fetch origin "$COMMIT1"
          git checkout -b "$PR_HEAD_BRANCH" "$COMMIT1"
          git push -u origin "$PR_HEAD_BRANCH"

      - name: Create pull request
        id: pr-create
        uses: ./.
        with:
          title: ${{ env.TITLE1 }}
          body: ${{ env.BODY1 }}
          update: ${{ matrix.update == 'update' }}
          force: ${{ matrix.force == 'force' }}
          draft: ${{ matrix.draft == 'draft' }}
          head_sha: ${{ case(matrix.use-head-sha == 'use-head-sha', env.COMMIT1, '') }}
          head: ${{ env.PR_HEAD_BRANCH }}
          base: ${{ env.PR_BASE_BRANCH }}

      - name: Get pull request using GitHub CLI
        env:
          PR_NUMBER: ${{ steps.pr-create.outputs.number }}
        run: gh pr view "$PR_NUMBER" --json "$GH_PR_FIELDS" | jq -S -f test/gh-cli-filter.jq >"$RUNNER_TEMP/github-cli.json"

      - name: Verify action output matches GitHub CLI output
        env:
          ACTION_OUTPUT_JSON: ${{ steps.pr-create.outputs.pull_request }}
        run: diff -u <(printf '%s' "$ACTION_OUTPUT_JSON" | jq -S -f test/action-output-filter.jq) "$RUNNER_TEMP/github-cli.json"

      - name: Verify pull request matches inputs
        env:
          PR_NUMBER: ${{ steps.pr-create.outputs.number }}
          PR_HTML_URL: ${{ steps.pr-create.outputs.html_url }}
          PR_HEAD_SHA: ${{ env.COMMIT1 }}
          PR_TITLE: ${{ env.TITLE1 }}
          PR_BODY: ${{ env.BODY1 }}
          PR_DRAFT: ${{ matrix.draft == 'draft' }}
        run: diff -u <(jq -n -S -f test/expected-filter.jq) "$RUNNER_TEMP/github-cli.json"

      - name: Update PR head branch
        if: ${{ matrix.use-head-sha != 'use-head-sha' }}
        working-directory: testing
        run: |
          git checkout "$PR_HEAD_BRANCH"
          git fetch origin "$COMMIT2"
          git reset --hard "$COMMIT2"
          git push --force -u origin "$PR_HEAD_BRANCH"

      - run: sleep 10
        if: ${{ matrix.use-head-sha != 'use-head-sha' }}

      - name: 'Run action with new inputs, update PR'
        id: pr-update
        continue-on-error: ${{ matrix.success != 'success' }}
        uses: ./.
        with:
          title: ${{ env.TITLE2 }}
          body: ${{ env.BODY2 }}
          update: ${{ matrix.update == 'update' }}
          force: ${{ matrix.force == 'force' }}
          draft: ${{ matrix.draft == 'draft' }}
          head_sha: ${{ env.COMMIT2 }}
          head: ${{ env.PR_HEAD_BRANCH }}
          base: ${{ env.PR_BASE_BRANCH }}

      - run: sleep 10

      - name: Get pull request using GitHub CLI
        env:
          PR_NUMBER: ${{ case(matrix.success == 'success', steps.pr-update.outputs.number, steps.pr-create.outputs.number) }}
        run: gh pr view "$PR_NUMBER" --json "$GH_PR_FIELDS" | jq -S -f test/gh-cli-filter.jq >"$RUNNER_TEMP/github-cli-2.json"

      - name: Verify action output matches GitHub CLI output
        if: ${{ matrix.success == 'success' }}
        env:
          ACTION_OUTPUT_JSON: ${{ steps.pr-update.outputs.pull_request }}
        run: diff -u <(printf '%s' "$ACTION_OUTPUT_JSON" | jq -S -f test/action-output-filter.jq) "$RUNNER_TEMP/github-cli-2.json"

      - name: Verify pull request matches inputs
        env:
          PR_NUMBER: ${{ case(matrix.success == 'success', steps.pr-update.outputs.number, steps.pr-create.outputs.number) }}
          PR_HTML_URL: ${{ case(matrix.success == 'success', steps.pr-update.outputs.html_url, steps.pr-create.outputs.html_url) }}
          PR_HEAD_SHA: ${{ case(matrix.success == 'success' && matrix.update == 'update', env.COMMIT2, env.COMMIT1) }}
          PR_TITLE: ${{ case(matrix.success == 'success' && matrix.update == 'update', env.TITLE2, env.TITLE1) }}
          PR_BODY: ${{ case(matrix.success == 'success' && matrix.update == 'update', env.BODY2, env.BODY1) }}
          PR_DRAFT: ${{ matrix.draft == 'draft' }}
        run: diff -u <(jq -n -S -f test/expected-filter.jq) "$RUNNER_TEMP/github-cli-2.json"

      - name: Delete pr branch
        if: ${{ always() }}
        run: git push origin ":$PR_HEAD_BRANCH"
        working-directory: testing
